In [225]:
import pandas as pd

prev_years = pd.read_csv("./Data/MarchMadnessResults-Compiled(1).csv")
stats = pd.read_csv("./Data/MarchMadnessStats(1).csv")

# Make sure college names match
Because our data set might have discrepencies in college names, we want to make sure they match. 
Ex. (Arizona St. is the same as Arizona State)

In [226]:
stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
stats[stats['TEAM'] == 'Arizona St.'] = 'Arizona State'
stats[stats['TEAM'] == 'Boise St.'] = 'Boise State'
stats[stats['TEAM'] == 'Cleveland St.'] = 'Cleveland State'
stats[stats['TEAM'] == 'Colorado St.'] = 'Colorado State'
stats[stats['TEAM'] == 'East Tennessee St.'] = 'East Tennessee State'
stats[stats['TEAM'] == 'Florida St.'] = 'Florida State'
stats[stats['TEAM'] == 'Fresno St.'] = 'Fresno State'
stats[stats['TEAM'] == 'Georgia St.'] = 'Georgia State'
stats[stats['TEAM'] == 'Grambling St.'] = 'Grambling State'
stats[stats['TEAM'] == 'Iowa St.'] = 'Iowa State'
stats[stats['TEAM'] == 'Jacksonville St.'] = 'Jacksonville State'
stats.loc[stats['TEAM'] == 'Kansas St.', 'TEAM'] = 'Kansas State'
stats.loc[stats['TEAM'] == 'Kennesaw St.', 'TEAM'] = 'Kennesaw State'
stats.loc[stats['TEAM'] == 'Kent St.', 'TEAM'] = 'Kent State'
stats.loc[stats['TEAM'] == 'Long Beach St.', 'TEAM'] = 'Long Beach State'
stats.loc[stats['TEAM'] == 'Louisiana-Lafayette', 'TEAM'] = 'Louisiana-Lafayette'
stats.loc[stats['TEAM'] == 'Michigan St.', 'TEAM'] = 'Michigan State'
stats.loc[stats['TEAM'] == 'Mississippi St.', 'TEAM'] = 'Mississippi State'
stats.loc[stats['TEAM'] == 'Montana St.', 'TEAM'] = 'Montana State'
stats.loc[stats['TEAM'] == 'Morehead St.', 'TEAM'] = 'Morehead State'
stats.loc[stats['TEAM'] == 'Murray St.', 'TEAM'] = 'Murray State'
stats.loc[stats['TEAM'] == 'NC St.', 'TEAM'] = 'NC State'
stats.loc[stats['TEAM'] == 'New Mexico St.', 'TEAM'] = 'New Mexico State'
stats.loc[stats['TEAM'] == 'Norfolk St.', 'TEAM'] = 'Norfolk State'
stats.loc[stats['TEAM'] == 'North Dakota St.', 'TEAM'] = 'North Dakota State'
stats.loc[stats['TEAM'] == 'Northwestern St.', 'TEAM'] = 'Northwestern State'
stats.loc[stats['TEAM'] == 'Ohio St.', 'TEAM'] = 'Ohio State'
stats.loc[stats['TEAM'] == 'Oklahoma St.', 'TEAM'] = 'Oklahoma State'
stats.loc[stats['TEAM'] == 'Oregon St.', 'TEAM'] = 'Oregon State'
stats.loc[stats['TEAM'] == 'Penn St.', 'TEAM'] = 'Penn State'
stats.loc[stats['TEAM'] == 'Pittsburg', 'TEAM'] = 'Pittsburgh'
stats.loc[stats['TEAM'] == 'San Diego St.', 'TEAM'] = 'San Diego State'
stats.loc[stats['TEAM'] == "Saint Mary's", 'TEAM'] = "Saint Mary's"
stats.loc[stats['TEAM'] == 'South Dakota St.', 'TEAM'] = 'South Dakota State'
stats.loc[stats['TEAM'] == 'Seton Hall', 'TEAM'] = 'Seton Hall'
stats.loc[stats['TEAM'] == 'Utah St.', 'TEAM'] = 'Utah State'
stats.loc[stats['TEAM'] == 'Washington St.', 'TEAM'] = 'Washington State'
stats.loc[stats['TEAM'] == 'Weber St.', 'TEAM'] = 'Weber State'
stats.loc[stats['TEAM'] == 'Wichita St.', 'TEAM'] = 'Wichita State'
stats.loc[stats['TEAM'] == 'Wright St.', 'TEAM'] = 'Wright State'

stats.loc[stats['TEAM'] == 'Pittsburg', 'TEAM'] = 'Pittsburgh'
stats.loc[stats['TEAM'] == 'SE Missouri St.', 'TEAM'] = 'Southeast Missouri State'
stats.loc[stats['TEAM'] == 'SE Missouri State', 'TEAM'] = 'Southeast Missouri State'

stats.loc[stats['TEAM'] == 'Satint Mary\'s', 'TEAM'] = 'Saint Mary\'s'
stats.loc[stats['TEAM'] == 'Louisiana Lafayette', 'TEAM'] = 'Louisiana-Lafayette'
stats.loc[stats['TEAM'] == 'Steton Hall', 'TEAM'] = 'Seton Hall'
prev_years.loc[prev_years['Team A'] == 'Satint Mary\'s', 'Team A'] = 'Saint Mary\'s'
prev_years.loc[prev_years['Team B'] == 'Satint Mary\'s', 'Team B'] = 'Saint Mary\'s'

prev_years.loc[prev_years['Team A'] == 'Pittsburg', 'Team A'] = 'Saint Mary\'s'
prev_years.loc[prev_years['Team B'] == 'Pittsburg', 'Team B'] = 'Saint Mary\'s'

prev_years.loc[prev_years['Team A'] == 'SE Missouri St.', 'Team A'] = 'Southeast Missouri State'
prev_years.loc[prev_years['Team A'] == 'Southeast Missouri St.', 'Team A'] = 'Southeast Missouri State'

prev_years.loc[prev_years['Team B'] == 'SE Missouri St.', 'Team B'] = 'Southeast Missouri State'
prev_years.loc[prev_years['Team B'] == 'Southeast Missouri St.', 'Team B'] = 'Southeast Missouri State'


prev_years.loc[prev_years['Team A'] == 'SE Missouri State', 'Team A'] = 'Southeast Missouri State'
prev_years.loc[prev_years['Team A'] == 'Southeast Missouri State', 'Team A'] = 'Southeast Missouri State'
prev_years.loc[prev_years['Team B'] == 'SE Missouri State', 'Team B'] = 'Southeast Missouri State'
prev_years.loc[prev_years['Team B'] == 'Southeast Missouri State', 'Team B'] = 'Southeast Missouri State'


prev_years.loc[prev_years['Team A'] == 'Steton Hall', 'Team A'] = 'Seton Hall'
prev_years.loc[prev_years['Team B'] == 'Steton Hall', 'Team B'] = 'Seton Hall'

C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\338391364.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Appalachian State' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  stats[stats['TEAM'] == 'Appalachian St.'] = 'Appalachian State'

In [227]:
stats_unique = sorted(stats['TEAM'].unique())

In [228]:
team_a_unique = sorted(prev_years['Team A'].unique())
team_b_unique = sorted(prev_years['Team B'].unique())

team_a_and_b_unique = list(team_a_unique + team_b_unique)

teams_not_in_stats = list(set(team_a_and_b_unique) - set(stats_unique))

print("Teams in prev_years but not in team_a_b stats:")
print(sorted(teams_not_in_stats))

Teams in prev_years but not in team_a_b stats:
[]

In [229]:
# get the y-variables
y = pd.DataFrame()
y["Team A Points"] = prev_years['Team A Points']
#y["Team B Points"] = prev_years['Team B Points']

#y = y.melt(value_vars=["Team A Points", "Team B Points"], var_name="Team", value_name="Points")

y

     Team A Points
0               54
1               72
2               71
3               68
4               79
..             ...
731             64
732             72
733             86
734             50
735             75

[736 rows x 1 columns]

In [230]:

df2 = pd.DataFrame(prev_years)
df1 = pd.DataFrame(stats)
team_a_stats = pd.merge(df2, df1, how='left', left_on=['Team A', 'Year'], right_on=['TEAM', 'YEAR'])
#display(team_a_stats)

team_b_stats = pd.merge(df2, df1, how='left', left_on=['Team B', 'Year'], right_on=['TEAM', 'YEAR'])
#display(team_b_stats)

team_a_stats = team_a_stats.drop(columns=['Year', 'Round', 'Team A', 'TEAM', 'CONF', 'Team B', 'Team A Points', 'POSTSEASON', 'YEAR', 'Team B Points', 'SEED'])

for col in team_b_stats.columns:
    if col not in ['Team B', 'Year', 'POSTSEASON', 'SEED', 'YEAR', 'TEAM', 'CONF', 'Team A Rank', 'Team B Points', 'Round', 'Team A', 'Team A Points', 'Team B Rank']:
        team_a_stats[f'B-{col}'] = team_b_stats[col]

team_a_stats['A-Win Perc'] = team_a_stats['W'] / team_a_stats['G'] 
team_a_stats['B-Win Perc'] = team_a_stats['B-W'] / team_a_stats['B-G'] 

team_a_stats = team_a_stats.drop(columns=['W', 'G', 'B-W', 'B-G'])


print(team_a_stats.columns)

display(team_a_stats)

Index(['Team A Rank', 'Team B Rank', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O',
       'EFG_D', 'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D',
       '3P_O', '3P_D', 'ADJ_T', 'WAB', 'B-ADJOE', 'B-ADJDE', 'B-BARTHAG',
       'B-EFG_O', 'B-EFG_D', 'B-TOR', 'B-TORD', 'B-ORB', 'B-DRB', 'B-FTR',
       'B-FTRD', 'B-2P_O', 'B-2P_D', 'B-3P_O', 'B-3P_D', 'B-ADJ_T', 'B-WAB',
       'A-Win Perc', 'B-Win Perc'],
      dtype='object')

,Team A Rank,Team B Rank,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,TORD,ORB,...,B-FTR,B-FTRD,B-2P_O,B-2P_D,B-3P_O,B-3P_D,B-ADJ_T,B-WAB,A-Win Perc,B-Win Perc
0,11,11,105.1,91.0,0.8396,51.1,44.4,20.7,23.6,36.5,...,37.0,36.9,52.3,44.0,37.3,36.7,64.8,2.5,0.823529,0.794118
1,16,16,100.1,109.7,0.2591,48.5,47.8,19.8,15.1,29.0,...,42.6,41.1,45.4,43.4,30.7,32.0,66.9,-11.5,0.363636,0.527778
2,13,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,31.3,28.5,49.3,50.6,37.7,30.2,66.0,0.3,NaN,0.705882
3,16,16,98.5,99.4,0.4736,47.6,48.7,17.2,21.1,29.6,...,45.6,31.6,53.1,51.1,38.0,37.2,69.3,-8.6,0.583333,0.588235
4,1,16,115.9,84.5,0.9743,50.6,44.8,18.3,27.0,38.2,...,42.6,41.1,45.4,43.4,30.7,32.0,66.9,-11.5,0.875,0.527778
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,4,11,120.8,96.8,0.9272,55.2,49.0,14.3,16.9,31.8,...,32.5,31.9,50.1,49.5,34.6,34.9,67.9,-0.6,0.75,0.611111
732,1,2,126.2,94.7,0.9644,56.0,47.7,16.5,14.0,37.4,...,34.3,35.8,51.6,44.3,34.2,31.4,69.2,5.8,0.878788,0.75
733,1,4,127.1,93.6,0.9712,57.1,45.1,14.9,16.2,36.5,...,35.2,39.6,57.6,51.1,36.5,31.9,72.5,3.4,0.911765,0.65625
734,11,1,114.0,101.2,0.7981,50.7,50.5,13.7,17.9,28.6,...,42.8,23.0,53.2,48.1,40.8,31.4,67.6,11.0,0.611111,0.878788
735,1,1,127.1,93.6,0.9712,57.1,45.1,14.9,16.2,36.5,...,42.8,23.0,53.2,48.1,40.8,31.4,67.6,11.0,0.911765,0.878788

In [231]:
import tensorflow as tf
from tensorflow import keras

ModuleNotFoundError: No module named 'tensorflow.python'

In [ ]:
#### Cross Validation (split data)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(team_a_stats, y, test_size=0.2, random_state=20)

In [ ]:
# Replacing NaN values with 0 in X_train
X_train = X_train.fillna(0)
X_test = X_test.fillna(0)
y_train = y_train.fillna(0)
y_test = y_test.fillna(0)

C:\Users\shust\AppData\Local\Temp\ipykernel_41956\3955844981.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X_train = X_train.fillna(0)
C:\Users\shust\AppData\Local\Temp\ipykernel_41956\3955844981.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X_test = X_test.fillna(0)

In [ ]:
model = keras.models.Sequential() # we have on layer followed by another layer in order. Some networks might be more integrated.

model.add(keras.layers.Flatten(input_shape=[28, 28])) # input layer

model.add(keras.layers.Dense(16, activation='relu')) # hidden layer
model.add(keras.layers.Dense(16, activation='relu')) # hidden layer
model.add(keras.layers.Dense(10, activation='softmax')) # softmax is basically what percentage of all z's is this particular z

#### Cross Validation (test data)
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

          42       0.00      0.00      0.00         1
          44       0.00      0.00      0.00         1
          46       0.00      0.00      0.00         1
          49       0.00      0.00      0.00         2
          51       0.00      0.00      0.00         1
          52       0.00      0.00      0.00         2
          53       0.00      0.00      0.00         3
          54       0.00      0.00      0.00         2
          55       0.00      0.00      0.00         4
          56       0.00      0.00      0.00         1
          57       0.00      0.00      0.00         1
          58       0.00      0.00      0.00         6
          59       0.00      0.00      0.00         3
          60       0.00      0.00      0.00         4
          61       0.00      0.00      0.00         6
          62       0.00      0.00      0.00         6
          63       0.00      0.00      0.00         4
          64       0.00      0.00      0.00         5
          65       0.00      0.00      0.00         5
          66       0.00      0.00      0.00         5
          67       0.00      0.00      0.00         3
          68       0.00      0.00      0.00         5
          69       0.00      0.00      0.00         4
          70       0.00      0.00      0.00         3
          71       0.00      0.00      0.00         2
          72       0.00      0.00      0.00         7
          73       0.00      0.00      0.00         4
          74       0.00      0.00      0.00         1
          75       0.00      0.00      0.00         2
          76       0.00      0.00      0.00         5
          77       0.00      0.00      0.00         3
          78       0.00      0.00      0.00         5
          79       0.02      1.00      0.04         3
          81       0.00      0.00      0.00         3
          82       0.00      0.00      0.00         3
          83       0.00      0.00      0.00         4
          84       0.00      0.00      0.00         3
          85       0.00      0.00      0.00         5
          86       0.00      0.00      0.00         3
          87       0.00      0.00      0.00         4
          89       0.00      0.00      0.00         3
          90       0.00      0.00      0.00         2
          93       0.00      0.00      0.00         2
          94       0.00      0.00      0.00         1
          95       0.00      0.00      0.00         1
          98       0.00      0.00      0.00         1
          99       0.00      0.00      0.00         1
         105       0.00      0.00      0.00         1
         109       0.00      0.00      0.00         1

    accuracy                           0.02       148
   macro avg       0.00      0.02      0.00       148
weighted avg       0.00      0.02      0.00       148

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

C:\Users\shust\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\shust\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\shust\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\shust\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='sgd',  # back propogation process (sgd is stochastic gradient descent)
    metrics=['accuracy']
)

In [ ]:
model.fit(X_train, y_train, epochs=30, validation_data=(X_valid, y_valid))